version: '3'

services:

  jupyter-hub:
    container_name: jupyterHub
    build:
      context: ./jupyterLab
      dockerfile: Dockerfile
    labels:
      name: JupyterHub Data Science
      description: Image that contains the most important tools for JupyterHub Data Science
      version: 1.0
    ports:
      - "8000:8000"
    restart: always
    networks:
      - backend
    volumes: 
      - ./notebooks:/home/admin/

networks:
  backend:
    driver: bridge